- internal/blockprocessor/committer.go
- internal/blockprocessor/committer_test.go
- internal/blockprocessor/dbadmin_tx_validator.go
- internal/blockprocessor/dbadmin_tx_validator_test.go
This commit validates DB index defined for the database. An index
for a database can be defined or updated for an existing database and
also can be defined when the db is created
Signed-off-by: senthil <snatara7@in.ibm.com>
> validate and commit index definition

- Makefile
- test/setup/cluster_setup_test.go
Once we run `make binary`, it is quite non-intuitive
to not see the binary on the `ls` output. Hence, it would
be better to unhide the .bin directory.
> rename .bin to bin

- internal/mptrie/mptrie.go
- internal/mptrie/proof.go
One of the previous commits missed returning the error within Update API if the empty key was put as a parameter to the function call. 
Another issue is within `GetProof` the error was compared with itself, i.e.
```
if err != err {
return nil, err
}
```
which obviously always false. This commit fixes it as well. 
Signed-off-by: Artem Barger <artem@bargr.net>
> Fix missing return of the error in mptrie

- internal/mptrie/mptrie.go
- internal/mptrie/node.go
Within the implementation of mptie there were a few nits, while using a switch to assert node type there is a way to leverage type knowledge to eliminate the need for casting variables later on. 
Signed-off-by: Artem Barger <artem@bargr.net>
> Use variable type while asserting within swith case

- sampleconfig/1node-shared-config-bootstrap.yml
- scripts/cryptoGen.sh
Now it's possible to run:
```
./scripts/cryptoGen.sh sampleconfig
```
given there is a docker image created with 
```
make docker
```
and next
```
docker run -it --rm -v $(pwd)/sampleconfig/:/etc/bcdb-server bcdb-container
```
will run the single instance of the BCDB
```
2021-07-02 22:27:45.607424 I | Starting a blockchain database
2021-07-02T22:27:45.699Z        INFO    bcdb-node1      bcdb/transaction_processor.go:97        Bootstrapping the ledger and database
2021-07-02T22:27:45.743Z        INFO    bcdb-node1      blockprocessor/processor.go:286 Registering listener [transactionProcessor]
2021-07-02T22:27:45.743Z        INFO    bcdb-node1      txreorderer/txreorderer.go:59   starting the transactions reorderer
2021-07-02T22:27:45.743Z        INFO    bcdb-node1 …
```
> Add script to generate crypto materials to run single node

- Makefile
- cmd/signer/signer.go
- cmd/signer/signer_test.go
- pkg/cryptoservice/signer.go
This commit adds an utility that can help the user to add
their digital signature on any data item. This would be used
when user submits query or transaction through `curl` command
> signer utility

- Makefile
- images/Dockerfile
- sampleconfig/config/1node-shared-config-bootstrap.yml
- sampleconfig/config/config.yml
- scripts/cryptoGen.sh
Crypto materials and configuration folders structure changed to folder structure used by car demo application
Crypto generation now done by dockerized openssl - see cryptoGen.sh
To create minimal crypto configuration, you can run:
```
./scripts/cryptoGen.sh sampleconfig
```
To create crypto configuration for more users/server, you can run:
```
./scripts/cryptoGen.sh sampleconfig <extra users>
```
For example, in case you want to generate crypto materials for extra users used in car demo, you can run:
```
./scripts/cryptoGen.sh sampleconfig alice bob dmv dealer
```
To generate docker image, after you generated crypto materials, run:
```
make docker
```
To invoke bcdb docker container, you can run:
```
docker run -it --rm -v $(pwd)/sampleconfig/:/etc/bcdb-server -p 6001:6001 -p 7050:7050 …
```
> Updating crypto material and docker image generation

- internal/bcdb/ledger_query_procesor_test.go
- internal/bcdb/transaction_processor_test.go
- internal/bcdb/worldstate_query_processor_test.go
- internal/blockprocessor/committer.go
- internal/blockprocessor/committer_test.go
- internal/blockprocessor/config_tx_validator_test.go
- internal/blockprocessor/data_tx_validator_test.go
- internal/blockprocessor/dbadmin_tx_validator_test.go
- internal/blockprocessor/processor_test.go
- internal/blockprocessor/test_util.go
- internal/blockprocessor/useradmin_tx_validator_test.go
- internal/blockprocessor/validator_test.go
- internal/identity/db_entries.go
- internal/identity/db_entries_test.go
- internal/identity/querier_test.go
- internal/worldstate/db.go
- internal/worldstate/leveldb/commit_and_query.go
- internal/worldstate/leveldb/commit_and_query_test.go
If we use one dbupdates for each tx in a block, we would do one sync write per tx.
As it degrades the performance, this PR makes one dbUpdates per database. As a result,
the number of sync writes would be equal to the number of dbs' data
modified in the block.
With this PR, the time taken to commit a block to worldstate reduced
from 150 msecs to 6 msecs
> fix dbupdates

- internal/bcdb/db.go
- internal/bcdb/mocks/db.go
- internal/bcdb/transaction_processor.go
- internal/bcdb/transaction_processor_test.go
- internal/blockcreator/blockcreator.go
- internal/blockcreator/blockcreator_test.go
- internal/blockcreator/mocks/replicator.go
- internal/comm/httptransport.go
- internal/errors/errors.go
- internal/replication/blockreplicator.go
- internal/replication/blockreplicator_test.go
- internal/replication/storage.go
- internal/replication/storage_test.go
- internal/replication/utils.go
- pkg/logger/logger.go
- pkg/server/server.go
- pkg/server/server_test.go
Import the etcd/raft lib module
Write the main loop that operates the RSM;
- Order(block)
- Deliver(block)
Assumptions:
- No dynamic config changes to membership
- Use (as module) the WAL from etcd 
- Use (copy) `Storage` from Fabric 
- No snapshots: don't create snapshots, don't accept snapshot
- Support node creation
- Support node shutdown and restart
- Test single node only
> Integrate raft node

- pkg/logger/logger.go
Bug reported in https://github.com/ibm-blockchain/bcdb-server/issues/116
A missing zap duration encoder in the logger config results is a
`panic: runtime error: invalid memory address or nil pointer dereference`
because the function pointer for the encoder is missing.
> Missing zap duration encoder

- internal/bcdb/ledger_query_procesor_test.go
- internal/bcdb/provenance_query_processor_test.go
- internal/bcdb/transaction_processor_test.go
- internal/bcdb/worldstate_query_processor_test.go
- internal/blockprocessor/data_tx_validator.go
- internal/blockprocessor/data_tx_validator_test.go
- internal/blockprocessor/validator.go
Validate the signatures on transactions in a block in parallel rather then serially, for performance.
First validate the signatures on each transaction in parallel, remembering the
set of users with valid signatures per TX. Then validate the fields, access control, operations, and MVCC serially.
`t.Parallel()` was removed from `internal/bcdb` unit tests because it creates an out-of-memory failure due to too many tests with `leveldb` running together.
> Parallel verification of signatures in a block

- internal/replication/blockreplicator_test.go
When a blockreplicaor is closed, Submit can result in either of two errors:
- closed error, or
- not-a-leader error;
depending on the scheduling of the threads.
> Flaky test: blockreplicator

- go.mod
- internal/stateindex/encoding.go
- internal/stateindex/encoding_test.go
- internal/stateindex/index_entries.go
- internal/stateindex/index_entries_test.go
When the indexed attribute value is a number, it can be
either a positive number or a negative number. Further, we
need to store these numbers in the indexDB while preserving
the order (i.e., 1 < 5) which is needed for performing range query
on the indexed attributes.
Hence, this commit identifies whether the value of an index attribute
is +ve or -ve and accordingly encoding them to preserve the order.
> Order preserving encoding of +ve/-ve value of indexed attribute

- internal/replication/blockreplicator_test.go
Normally the block replicator ingests about 100 blocks before it is closed.
However, in rare scheduling conditions the loop will end submitting 1000 blocks
before the block-replicator is closed. The wg.Done() in blockreplicator_test.go
L:227 function submitManyTillClosed was located in the wrong place for that rare event.
Its location was changed to handle this case as well.
> Flaky test: block replicator timeout

- internal/mptrie/mptrie_test.go
- internal/mptrie/store/open.go
- internal/mptrie/store/update_and_query.go
Removed second unmarshal call in `GetNode`
Replaced `json.Marshal` and `json.Unmarshal` in `GetNode` and `PutNode` by `proto.Marshal` and `proto.Unmarshal`
Worth to mention strange bug in `proto.Unmarshal` - once unmarshaling `BranchNode.Children`, slice of slices of bytes, for some reason, `nil` replaced by empty slice `[]byte{}`. For example, if before call to marshal `node.Children[i] == nil` was `true`, after unmarshal `node.Children[i] != nil && len(node.Children[i]) == 0` is `true`, 
> Remove second unmarshall in mptrie store GetNode call

- internal/replication/blockreplicator.go
- internal/replication/blockreplicator_test.go
- internal/replication/env_test.go
- internal/replication/utils.go
Dynamic config of ClusterConfig is currently not supported and causes panic.
This commit allows config changes to ClusterConfig.Admins and ClusterConfig.CertAuthConfig,
as those have no effect on the replication component.
The server will panic if ClusterConfig.Nodes or ClusterConfig.ConsensusConfig are changed.
This will change once dynamic reconfig of consensus related objects is implemented.
> Allow config updates to Admins & CAs

- internal/bcdb/ledger_query_procesor.go
- internal/bcdb/ledger_query_procesor_test.go
- internal/bcdb/transaction_processor_test.go
- internal/blockprocessor/committer.go
- internal/blockprocessor/processor_test.go
- internal/mptrie/mptrie.go
- internal/mptrie/node.go
- internal/mptrie/proof.go
- internal/mptrie/proof_test.go
- pkg/state/proof.go
Moving internal `mptrie.Proof` struct to pkg `state.Proof` with all relevant methods. 
To make it available to sdk.
> Mptrie proof api moving to pkg

- internal/blockprocessor/committer.go
- internal/blockprocessor/committer_test.go
- internal/stateindex/index_entries.go
- internal/stateindex/index_entries_test.go
To enable logical operations such as <, >, <=, >=, we introduce
two additional fields in the index entry: ValuePosition and
KeyPosition.
Further, we unexport certain fields/functions and export some
which are to be used by query executor package
> Update index entries structure

- internal/replication/blockreplicator.go
- internal/replication/blockreplicator_3node_test.go
- internal/replication/blockreplicator_test.go
- internal/replication/env_test.go
This commit:
- Adds code that allows each single node to create a stream of snapshots based on accumulated size criteria.
- The last 4 snapshots are saved, older snapshots are purged.
- The WAL is also pruned (compacted) when a snapshot is created.
- A single node can restart from its own snapshot.
However:
- Catch up between leader and follower not supported yet. Therefore,
- For a cluster scenario use snapshot-inteval that will never cause a snapshot, e.g. max-int64.
> Take snapshots & restart from snapshot

- internal/httphandler/config_request_handler.go
- internal/httphandler/config_request_handler_test.go
- internal/httphandler/data_request_handler.go
- internal/httphandler/db_request_handler.go
- internal/httphandler/db_request_handler_test.go
- internal/httphandler/ledger_request_handler.go
- internal/httphandler/ledger_request_handler_test.go
- internal/httphandler/provenance_request_handler.go
- internal/httphandler/tx_handler.go
- internal/httphandler/users_request_handler.go
- internal/httphandler/users_request_handler_test.go
- internal/httphandler/utils.go
- internal/httphandler/utils_test.go
- internal/httputils/utils.go
- internal/httputils/utils_test.go
Moving 3 functions from `httphandler/utils.go` to a leaf package in `httputils/utils.go`.
These functions will be used in the next commit, that introduces the http catch-up service in the comm package.
No functional change.
> Refactor http utilities to common package

- internal/comm/catchup_client.go
- internal/comm/catchup_client_test.go
- internal/comm/catchup_handler_test.go
- internal/comm/httptransport.go
- internal/httputils/utils.go
The catchup client exposes methods that allow the block replicator to catch-up
with the cluster. It communicated with the catch-up service exposed by each peer.
> Catchup client

- internal/blockprocessor/committer_test.go
- internal/stateindex/encoding.go
- internal/stateindex/encoding_test.go
- internal/stateindex/index_entries_test.go
When we use order preserving encoded bytes of number in the
index entry, the json marshaler converts the bytes to base64
encoding which does not preserve the order.
This commit use hex encoding to convert a given number into
an order preserving string.
> order preseving encoding for +ve and -ve numbers

- internal/comm/catchup_client.go
- internal/comm/catchup_client_test.go
- internal/comm/httptransport.go
- internal/httputils/utils.go
- internal/replication/blockreplicator.go
- internal/replication/blockreplicator_3node_test.go
- internal/replication/env_test.go
Perform catch-up at block replicator
When a node lags behind the cluster more than the last checkpoint of the leader, the leader will send a snapshot to it. A snapshot is a block with some raft information. A received snapshot serves as a trigger for the node to perform catch-up, or state transfer.
It will contact one of the active members of the cluster (preferably the leader), and will request the missing blocks up to the block indicated by the snapshot.
> Catchup at block replicator

- internal/blockprocessor/committer_test.go
- internal/stateindex/index_entries.go
- internal/stateindex/index_entries_test.go
As 0 is the default value when we unmarshal or create an index entry object, we could do some mistake or introduce bug in the test code when the enum for certain fields in the object start with 0. Hence, this commit start the index position enum at 1 instead of 0
> start index position enum (Beginning, Existing, Ending) from 1 instead of 0

- internal/bcdb/transaction_processor.go
- internal/bcdb/transaction_processor_test.go
- internal/queue/pending_txs.go
- internal/queue/pending_txs_test.go
- internal/queue/promise.go
- internal/queue/promise_test.go
- Fix a bug in the promise were the channel was closed by the receiver, not the sender.
- Add the ability to complete the promise with an error result.
- Refactor the pending txs queue and the promise to the `queue` package.
- Add more unit testing.
> Refactor pending TX queue

- internal/replication/blockreplicator_test.go
Address the test flake in TestBlockReplicator_Submit/normal_flow:_blocked_submit
as described in issue #195
> test flake in TestBlockReplicator_Submit

- internal/bcdb/transaction_processor.go
- internal/blockcreator/blockcreator.go
- internal/blockcreator/blockcreator_test.go
- internal/queue/pending_txs.go
- internal/queue/pending_txs_test.go
- internal/replication/blockreplicator.go
- internal/replication/env_test.go
- Add a ReleaseWithError method to PendingTxs queue
- Add a link to PendindTxs queue to block-creator & block-replicator
- Functinality of block-creator & block-replicator in later commits
> Release transactions with error from PendingTxs

- internal/blockcreator/blockcreator.go
- internal/blockcreator/blockcreator_test.go
- internal/httputils/blocks.go
- internal/httputils/blocks_test.go
When the replicator rejects a block, release TXs in the block from the PendingTxs queue.
> Release txs in block-creator

- .github/workflows/deploy-docusaurus.yml
For pull-request, build the documentation. This will catch all errors before merging the PR.
For push-request, build and deploy the documentation. This will deploy the pages on `gh-pages` channel. 
> build doc on pull request but don't deploy

- pkg/logger/logger.go
- pkg/logger/logger_test.go
Allowing zap.Options in the logger will allow us to insert zap.Hooks.
This will allow us to catch log messages during unit testing, and test
events that are difficult to observer otherwise.
> Allow zap.Options in logger

- Makefile
- cmd/base64_encoder/encoder.go
- cmd/base64_encoder/encoder_test.go
This commit adds an utility that can encode the given data to
base64 string. Note that this utility accepts either a JSON or
string value only.
> encoder for value

- config/ca_config.go
- config/ca_config_test.go
- config/config.go
- config/config_test.go
- config/shared_config.go
- config/testdata/config.yml
- deployment/config-docker/config.yml
- internal/bcdb/db.go
- internal/bcdb/transaction_processor.go
- internal/comm/catchup_client.go
- internal/comm/catchup_client_test.go
- internal/comm/httptransport.go
- internal/comm/httptransport_catchup_test.go
- internal/comm/httptransport_test.go
- internal/comm/log_adapter.go
- internal/replication/blockreplicator_test.go
- internal/replication/env_test.go
- pkg/certificateauthority/ca_chain.go
- pkg/certificateauthority/ca_chain_test.go
Support TLS for peer server to server communication.
The server accepts only TLS connections, the client dials TLS.
Client authentication is not yet supported (future commit).
Client authorization is not yet supported (future commit).
Some utilities where added to load the CA certificates from disk, verify them,
and pack then all into a single bundle, as the rafthttp transport expects.
> TLS support for comm

- Makefile
- cmd/base64_decoder/decoder.go
- cmd/base64_decoder/decoder_test.go
This commits add a decoder utility that would decode
a given json data response envelope.
It will get updated to decode the bas64 encoded value
in the subsequent PR.
> decoder decodes data response envelope

- internal/blockprocessor/config_tx_validator.go
- internal/blockprocessor/config_tx_validator_test.go
- internal/replication/utils.go
- internal/replication/utils_test.go
Define the rules for updating the ConsensusConfig, in particular, the Memebrs.
The core contribution is the VerifyConsensusReConfig method, that checks the configuration changes in types.ConsensusConfig.
This method checks that the changes between one ConsensusConfig to the next are safe, because some mutations might
cause a permanent loss of quorum in the cluster, something that is very difficult to recover from.
- Members can be added or removed (membership change) one member at a time
- Members' endpoints cannot be changed together with a membership change
- An existing member cannot change its Raft ID (it must be removed from the cluster and added again as a new member)
- The Raft ID of a new member must be unique - therefore it must be larger than MaxRaftId
We assume that both the …
> ConsensusConfig reconfig rules

- internal/bcdb/transaction_processor.go
- internal/comm/catchup_client_test.go
- internal/comm/httptransport.go
- internal/comm/httptransport_catchup_test.go
- internal/comm/httptransport_test.go
- internal/replication/blockreplicator_test.go
- internal/replication/env_test.go
Allow the HTTPTransport to update its member peers - add peer / remove peer / change peer endpoint.
This includes both the raft http transport and the catchup client.
Note: a config TX that adds or removes peers is not yet supported (future commit).
> Re-config comm transport endpoints

- internal/blockprocessor/processor.go
- internal/replication/blockreplicator.go
- internal/replication/blockreplicator_3node_test.go
- internal/replication/blockreplicator_reconfig_test.go
Allow a config Tx that changes the endpoint of an existing PeerConfig.
Note: a config TX that adds or removes peers is not yet supported (future commit).
> Re-config cluster endpoints

- internal/httputils/blocks.go
- internal/httputils/blocks_test.go
- internal/replication/blockreplicator.go
- internal/replication/blockreplicator_reconfig_test.go
- internal/replication/env_test.go
- internal/replication/utils.go
- internal/replication/utils_test.go
Handle a config TX that carries a membership change, i.e. adding or removing a member peer.
If a config transaction carries changes to the cluster membership, i.e. add or remove a node, it is proposed
using Raft’s ProposeConfChange(), with the config-block as Context field of the proposal.
This allows consensus on the new Raft membership, while consenting on the new config-block at the same time.
If the config tx does not carry changes to the cluster membership it is proposed using the normal Propose().
Implement peer removal and addition, but test only removal.
- When a node is removed, it is recommended to shutdown the removed node prior to proposing the removal config-tx.
- If the removed node is alive, it detects its own removal after it commits and then shuts down the replication …
> Re-config cluster membership: peer removal

- internal/blockprocessor/config_tx_validator_test.go
- internal/replication/blockreplicator.go
- internal/replication/blockreplicator_reconfig_test.go
- internal/replication/utils.go
- internal/replication/utils_test.go
Allow a config-tx to carry a membership change that adds a peer.
Test that the peer was added to the existing cluster.
Note that bootstrapping the peer is not yet supported (future commit).
> Re-config cluster membership: peer addition

- internal/blockprocessor/config_tx_validator.go
- internal/blockprocessor/validator.go
Eliminate some code duplication when validating the genesis block (block number 1).
No functional change.
> Validate genesis block: code hygiene

- internal/bcdb/transaction_processor.go
- internal/blockprocessor/committer.go
- internal/blockprocessor/committer_test.go
- internal/blockprocessor/processor.go
- internal/blockprocessor/processor_test.go
- internal/txvalidation/config_tx_validator.go
- internal/txvalidation/config_tx_validator_test.go
- internal/txvalidation/data_tx_validator.go
- internal/txvalidation/data_tx_validator_test.go
- internal/txvalidation/dbadmin_tx_validator.go
- internal/txvalidation/dbadmin_tx_validator_test.go
- internal/txvalidation/sig_validator.go
- internal/txvalidation/useradmin_tx_validator.go
- internal/txvalidation/useradmin_tx_validator_test.go
- internal/txvalidation/validator.go
- internal/txvalidation/validator_test.go
In preparation for implementing config-tx validation pre-order (future commit), we separate the tx-validation logic into a separate package.
- All validation code was moved to a new package
- Respective types & methods used in other packages made Public (e.g. ValidateBlock)
- The block processor consumes a single method during commit: 'ValidateBlock'.
- Generation of Validator extracted from inside the block processor, now in transaction processor
- Validator now can be shared with other components (future commit)
The block processor consumes a single method during commit: 'ValidateBlock'.
This will make it easier to expose validation logic to pre-ordering components.
This commit presents **no functional change**, just refactoring of existing code.
> Separate tx validation from block processor

- go.mod
- internal/comm/httptransport.go
- internal/comm/httptransport_test.go
- internal/replication/blockreplicator_reconfig_test.go
1. Utilize the rafthttp transport method that reports active peers.
2. Register the raft endpoints correctly to the ServeMux.
3. Expose a new method comm.HTTPTransport.ActivePeers, this will be used in the API that reports the cluster status (future commit).
4. Correct unit tests in comm and replication in light of the fix in (2).
After registering the raft endpoints correctly (2), the nodes may connect in an asymmetric way, that is:
- say the shared cluster config defines: (node1  localhost:1001) (node2  localhost:1002) (node3 localhost:1003)
- and: node1 binds to 1001, node2 binds to 1002
- but: node3 binds to 1004
- then: the connectivity is asymmetric - node3 can reach node1 & node2 but not the other way around
This may happen when reconfiguring an endpoint: node3 from 1003 -> 1004; …
> HTTPTransport reports active peers

- config/shared_config.go
- config/shared_config_test.go
- internal/bcdb/transaction_processor_test.go
- pkg/server/server_test.go
- test/setup/cluster_setup.go
- test/setup/config_writer_test.go
Change the **SharedConfiguration** field Nodes
from
- Nodes []NodeConf
to
- Nodes []*NodeConf
> Refactor SharedConfiguration

- internal/bcdb/transaction_processor.go
- internal/bcdb/transaction_processor_test.go
- internal/replication/blockreplicator.go
- internal/replication/blockreplicator_reconfig_test.go
- internal/replication/blockreplicator_test.go
- internal/replication/env_test.go
- internal/replication/raft_http_error.go
A new node in the cluster bootstraps with a join block, which is a config block that includes it in the Nodes and Members arrays.
The new nodes initializes comm.HTTPTransport with the peers from the join block, and therefore  can reach all the current active peers.
The node starts by on-boarding, that is, fetching all the blocks from 1 (genesis) and the  join-block number (say, J). As it receives blocks, it commits them to the ledger and databases,     rebuilding the state. If the node crashes befor reaching block J, it will resume on-boarding from where it stopped.
When the node reaches the join-block, it uses the cluster config within to construct a raftpb.ConfState,     it reads the raft Index and Term, and initializes the raft-storage (WAL & memory) to signal to raft     that it had …
> Cluster bootstrap join in replication

- config/join_block.go
- config/join_block_test.go
- internal/blockcreator/blockcreator.go
- internal/blockstore/commit_and_query.go
- internal/comm/catchup_client.go
- internal/comm/catchup_handler.go
- internal/comm/catchup_handler_test.go
- internal/httphandler/config_request_handler.go
- internal/httphandler/config_request_handler_test.go
- internal/httphandler/data_request_handler.go
- internal/httphandler/db_request_handler.go
- internal/httphandler/ledger_request_handler.go
- internal/httphandler/ledger_request_handler_test.go
- internal/httphandler/provenance_request_handler.go
- internal/httphandler/tx_handler.go
- internal/httphandler/users_request_handler.go
- internal/httphandler/utils.go
- internal/replication/blockreplicator.go
- internal/replication/blockreplicator_3node_test.go
- internal/replication/env_test.go
- internal/replication/raft_http_error.go
- internal/utils/blocks.go
- internal/utils/blocks_test.go
- internal/utils/http.go
- internal/utils/http_test.go
- test/setup/cluster_setup_test.go
- test/setup/config_writer_test.go
Rename `httputils` package to `utils`
Rename file `utils.go` to `http.go`
No functional change.
> Rename httputils package to utils

- internal/queue/promise_test.go
Cannot access the front of the promise with two different go-routine.
> Data race in queue tests

- internal/replication/blockreplicator.go
- internal/replication/blockreplicator_3node_test.go
When a new leader is elected, we have to prevent new proposals until it commits all the in-flight blocks.
> New leader with in-flight blocks

- config/ca_config_test.go
- internal/bcdb/transaction_processor_test.go
- internal/blockprocessor/processor_test.go
- internal/comm/httptransport_test.go
- internal/httphandler/config_request_handler_test.go
- internal/httphandler/data_request_handler_test.go
- internal/httphandler/db_request_handler_test.go
- internal/httphandler/ledger_request_handler_test.go
- internal/httphandler/provenance_request_handler_test.go
- internal/httphandler/users_request_handler_test.go
- internal/httphandler/utils_test.go
- internal/txvalidation/config_tx_validator_test.go
- internal/txvalidation/data_tx_validator_test.go
- internal/txvalidation/dbadmin_tx_validator_test.go
- internal/txvalidation/useradmin_tx_validator_test.go
- internal/txvalidation/validator_test.go
- pkg/certificateauthority/ca_chain_test.go
- pkg/cryptoservice/signer_test.go
- pkg/server/testutils/crypto_utils.go
As follow-up to TLS pr, added renaming to Create/Load test certificates utility methods.
> Server test crypto utilities rename

- internal/bcdb/ledger_query_procesor.go
- internal/bcdb/ledger_query_procesor_test.go
- internal/httphandler/ledger_request_handler.go
Support requesting the ledger path from a block to itself.
When start block is zero the server entered to an endless loop.
> Ledger path from block to itself

- internal/bcdb/db.go
- internal/replication/blockreplicator.go
- internal/replication/blockreplicator_reconfig_test.go
After adding a node, and restarting the server, the block replicator needs
to avoid re-committing a block that was created during membership config changes,
but apply the 'ConfChangeV2' to the raft state machine. This may happen when:
- existing nodes apply a config change but then restart from a snapshot that happened prior to the config change block;
- a node joins an existing cluster, as on-boarding brings all the ledger from a remote peer, and then we start raft.
must avoid re-committing the block,
> Restart after reconfig: add node

- internal/provenance/commit_and_query.go
- internal/provenance/commit_and_query_test.go
When the key is deleted from the world state in
a one block and the same key is added in the future
block, there should be two links (previous/next) between old deleted
value and the new value. Due to a mistake in the unit-test,
we missed to detect the bug in the production code.
Now with the integration test, we could detect this bug.
To get the last deleted value to construct the next/previous
link with the new value, we need to pass the correct key. The
existing code passes the incorrect key to find the last deleted
key node.
> fix backward link to deleted key in provenance

- internal/replication/blockreplicator_3node_test.go
- internal/replication/blockreplicator_reconfig_test.go
- internal/replication/env_test.go
- test/setup/server_setup.go
Solves #428 
This commit adds a `destroyClusterEnv()` method that closes all the nodes that were started and removes the environment directory.
Each test, calls `defer destroyClusterEnv(t, env)` right after the environment is created to make sure it will be destroyed
even in the case of test failure.
> Destroys cluster environment when a test fails

- internal/bcdb/db.go
- internal/bcdb/mocks/db.go
- internal/bcdb/provenance_query_processor.go
- internal/bcdb/provenance_query_processor_test.go
- internal/httphandler/provenance_request_handler.go
- internal/httphandler/provenance_request_handler_test.go
Operations such as reads, writes, and deleted
performed by an user can be retrieved either by
the respective user or by the admin only.
> provenance acl: for operations APIs

- .gitignore
- internal/httphandler/data_request_handler.go
- internal/httphandler/data_request_handler_test.go
- internal/httphandler/ledger_request_handler_test.go
- internal/httphandler/utils.go
- internal/utils/http.go
- pkg/constants/http.go
- pkg/constants/http_test.go
- pkg/server/server_test.go
- test/data/data_tx_test.go
- test/queries/ledger_test.go
- test/queries/provenance_acl_test.go
- test/queries/provenance_switch_off_test.go
- test/queries/range_query_test.go
- test/setup/config_writer.go
- test/user/user_db_acl_test.go
> Encode keys in URLs with base64url raw

- Makefile
E.g., `make GO=go1.19.4 binary`
> Allow setting different go version from the command line

- go.mod
- internal/worldstate/leveldb/cache.go
- internal/worldstate/leveldb/cache_test.go
- internal/worldstate/leveldb/commit_and_query.go
- internal/worldstate/leveldb/commit_and_query_test.go
- internal/worldstate/leveldb/open.go
- internal/worldstate/leveldb/open_test.go
- internal/worldstate/leveldb/snapshot.go
- internal/worldstate/leveldb/snapshot_test.go
- Replacing map with sync.Map
- Caching DB snapshot after commit to avoid creating a snapshot for each Get operation
- Modifying cache to return byte array to avoid code duplication
- Remove Db lock because levelDB is already protected
- Reduce code duplication in Open()
> Cache LevelDB snapshots and use lock-free map
