internal/bcdb/db.go, internal/bcdb/path.go, internal/bcdb/transaction_processor.go, internal/bcdb/transaction_processor_test.go, internal/blockprocessor/committer.go, internal/blockprocessor/committer_test.go, internal/blockprocessor/processor.go, internal/blockprocessor/processor_test.go, internal/blockprocessor/test_util.go, internal/mptrie/mptrie.go, internal/mptrie/mptrie_test.go, internal/mptrie/node.go, internal/mptrie/proof_test.go, internal/mptrie/store/open_test.go, internal/mptrie/store/update_and_query.go
Integration with block processor and tx processor
=> Merkle-Patricia trie - step four - integration (#421)

pkg/logger/logger.go, pkg/logger/logger_test.go
=> Add With() to logger

Makefile, images/Dockerfile, sampleconfig/1node-shared-config-bootstrap.yml, sampleconfig/config.yml
Create a docker image with bcdb server
Signed-off-by: Artem Barger <artem@bargr.net>
=> Add Dockerfile and one node sample configs

docs/curl/build.md
=> Adding docker build section to docs/curl/build.md

internal/stateindex/index_entries.go, internal/stateindex/index_entries_test.go, internal/worldstate/db.go, internal/worldstate/leveldb/commit_and_query.go, internal/worldstate/leveldb/commit_and_query_test.go
This commit creates index entries whenever a block commit happens
=> Create index entries

internal/mptrie/store/update_and_query.go
=> sync write to state trie store

internal/blockstore/commit_and_query.go
Currently, we are doing so many serial sync writes
to metadata databases in the block store. This commit
uses batch writes and goroutines to parallelize these
sync writes.
As existing recovery logic is robust, node failure during
any parallel operations is not a problem.
the commit time to block store reduced by 20%
=> parallel commit to metadataDB in blockstore

internal/mptrie/mptrie.go, internal/mptrie/store/update_and_query.go, internal/mptrie/store/update_and_query_test.go
Improving MPTrie.persistsSubtrie performance.
=> Improving MPTrie performance

internal/blockprocessor/config_tx_validator.go, internal/blockprocessor/config_tx_validator_test.go, internal/blockprocessor/validator_test.go
Prevent config transactions that change the Nodes or ConsensusConfig from commit
by marking them invalid. This is until dynamic re-config is implemented.
=> Mark dynamic config invalid

internal/queryexecutor/executor.go, internal/queryexecutor/executor_test.go, pkg/constants/query.go
A query comes with multiple attributes each with certain
conditions. This commit converts the query condition into
internal structure for simpler use.
=> Validate and disect attributes' conditions in a query

internal/blockprocessor/committer.go, internal/blockprocessor/committer_test.go, internal/queryexecutor/execute_conditions.go, internal/queryexecutor/execute_conditions_test.go, internal/stateindex/encoding.go, internal/stateindex/encoding_test.go, internal/stateindex/index_entries.go, internal/stateindex/index_entries_test.go, internal/worldstate/leveldb/commit_and_query_test.go
Before committing the changes to the world state database, construct index entries and commit to the world state database.
=> Commit index entries to worldstate

LICENSE
=> include Apache License 2.0

Makefile, docs/curl/build.md, images/Dockerfile, sampleconfig/config/1node-shared-config-bootstrap.yml, sampleconfig/config/config.yml
=> Update docker build

internal/blockcreator/blockcreator.go, internal/blockcreator/blockcreator_test.go, internal/replication/blockreplicator.go, internal/replication/blockreplicator_3node_test.go, internal/replication/blockreplicator_test.go
The block replicator is made in charge of numbering the blocks and setting the last header base hash.
The block replicator keeps track of the last committed block, and the last proposed block, and
updates them whe leadership is assumed and lost.
The block numbers given the block creator are provisional, and number the sequence of proposals since
the node started its current incarnation.
=> Block numbering in replicator

internal/bcdb/transaction_processor.go, internal/bcdb/transaction_processor_test.go, internal/errors/errors.go, internal/httphandler/tx_handler.go, pkg/constants/http.go, pkg/constants/http_test.go
=> Check TxId is a URL segment-nz

internal/replication/blockreplicator.go
When closing the replicator, in one case, the replicator's event-loop go-routine breaks out
of the loop without broadcasting to the propose-loop sync.Cond, and the propose loop remains
waiting on it and does not exit.
The solution is to broadcast to the sync.Cond when the event-loop go-routine exits, not only
when it detects the stop signal.
=> Solve replicator close deadlock

internal/comm/catchup_client_test.go
Eliminate flake by removing sleep, use zap.Hooks instead.
=> Unit test flake

docs/getting-started/guide.md, docs/getting-started/launching-one-node/docker.md, docs/getting-started/pre-requisite/gosdk.md, docs/getting-started/transactions/gosdk/datatx.md, docs/getting-started/transactions/gosdk/dbtx.md, docs/getting-started/transactions/gosdk/usertx.md
=> Updating sdk transactions, docker documentation and broken links

images/README.md
=> Updated images/README.md

docs/getting-started/proofs-and-verification/curl/block.md, docs/getting-started/proofs-and-verification/curl/ledger.md, docs/getting-started/proofs-and-verification/curl/state.md, docs/getting-started/proofs-and-verification/gosdk/block.md, docs/getting-started/queries/curl/provenance.md
=> Overview of ledger API

images/README.md
=> Fix image name in README

docs/getting-started/launching-one-node/binary.md, docs/getting-started/launching-one-node/crypto-materials.md, sidebars.js
=> Adding cryptoGen.sh documentation.

docs/getting-started/guide.md, docs/getting-started/launching-one-node/binary.md, docs/getting-started/launching-one-node/overview.md, docs/introduction.md
Signed-off-by: Hanan Singer <hanan@il.ibm.com>
=> Updated readme - first pr

internal/bcdb/transaction_processor.go, internal/bcdb/transaction_processor_test.go, internal/replication/blockreplicator.go
When boostrap.method is 'join' the config loads a config block from a binary file.
The boostrapping sequence of the server is changed. Instead of generating the genesis
block, from the shared-config object, the server gets a config block (a.k.a. the join-block).
The server selects from where to take the cluster config: (1) from the DB, or (2) the
join-block; depending on which is more recent. The server then starts the transport and
replication components with the most recent cluster-config, and also lets the replication
have the join-block.
Note: the functionality in the replication component that does on-boarding is not yet
implemented (future commit).
=> Cluster bootstrap join server

MAINTAINERS.md, README.md
README.md now points to hypeledger labs docs site
=> Updated README.md and MAINTAINERS.md

internal/replication/blockreplicator.go, internal/replication/blockreplicator_reconfig_test.go
We are preventing all proposals when a config is in flight, by using the same mechanism that prevents proposals when there are too many regular blocks in flight. This is not strictly necessary (what we strictly need is to prevent proposing a config when another config is in-flight), but is easier to implement. The implications on steady state performance are negligible, as config transactions are rare.
=> Prevent proposals inflight config

internal/replication/blockreplicator_3node_test.go, internal/replication/blockreplicator_reconfig_test.go
=> Data race in replication unit tests

go.sum, test/setup/cluster_setup.go, test/setup/server_setup.go, test/user/user_db_acl_test.go
=> test user addition and acl on database

deployment/kube/README.md, deployment/kube/single-file/orion-minimal.yaml, deployment/kube/using-secrets/orion-deployment.yaml, deployment/kube/using-secrets/orion-importsecrets.sh, deployment/kube/using-secrets/orion-namespace.yaml, deployment/kube/using-secrets/orion-service.yaml, deployment/kube/using-secrets/orion-volumes.yaml
One deployment
One service - checked only with Docker Desktop
One persistent volume claim
Certificates and configurations passed as secrets and secret mapped to volumes
=> Simple kubernetes deployment

internal/txvalidation/dbadmin_tx_validator.go, internal/txvalidation/dbadmin_tx_validator_test.go
=> disabling update of index of an existing db 

test/cluster/basic_test.go, test/cluster/catchup_test.go, test/setup/server_setup.go
=> Catchup tests

internal/replication/blockreplicator.go
Make sure a raftpb.EntryConfChange entry does not create a snapshot with an empty block.
Also get rid of a few warning (unhandled error, context leak).
=> Improve snapshot creation safety

pkg/server/mock/rest_client.go, test/db/db_index_management_test.go, test/setup/server_setup.go, test/user/user_db_acl_test.go
=> test database management: creation, deletion, index

.github/workflows/docker-buildx.yml, .github/workflows/docker.yml, .github/workflows/go.yml, Makefile
Support for multiarch docker build
=> Docker multiarch

images/README.md
=> Fixed volumes path in documentation

test/cluster/catchup_test.go, test/setup/cluster_setup.go, test/setup/server_setup.go
=> Fix catchup test

test/cluster/catchup_test.go
=> fix catchup bug

test/cluster/catchup_test.go, test/cluster/config_admin_test.go, test/setup/cluster_setup.go, test/setup/server_setup.go
=> config tests: admins and CAs

Makefile, images/Dockerfile, scripts/tlsGen.sh
=> Fixing tls certificates generation script and local docker multiarch

test/cluster/basic_test.go, test/cluster/catchup_test.go, test/data/data_tx_test.go, test/setup/server_setup.go
=> data tx integration test

internal/httphandler/ledger_request_handler_test.go, pkg/server/mock/rest_client.go, test/queries/ledger_test.go, test/queries/port_allocation.go, test/setup/cluster_setup.go, test/setup/server_setup.go
=> Ledger API test: blocks

pkg/server/server.go
=> Start server while on-boarding

pkg/server/testutils/crypto_utils.go, test/cluster/catchup_test.go, test/cluster/config_admin_test.go, test/cluster/config_ca_test.go, test/cluster/config_raft_test.go, test/setup/server_setup.go
=> GetClusterConfig accessibility test

internal/txvalidation/config_tx_validator.go, internal/txvalidation/config_tx_validator_test.go
=> Allow host-names for nodes

test/user/user_db_acl_test.go, test/user/user_error_cases_test.go
=> testing user tx error cases

test/cluster/remove_node_test.go
=> Dynamic cluster - remove node tests

internal/provenance/commit_and_query.go, internal/provenance/commit_and_query_test.go, pkg/server/mock/rest_client.go, pkg/server/server_test.go, test/queries/provenance_test.go, test/setup/server_setup.go
This commit covers all historical data apis
1. GetAllValues()
2. GetValueAt()
3. GetNextValues()
4. GetPreviousValues()
5. GetMostRecentValueAtOrBelow()
=> provenance queries test: historical data api

pkg/server/mock/rest_client.go, test/cluster/add_node_test.go, test/setup/cluster_setup.go, test/setup/server_setup.go
=> Dynamic cluster - add node test

test/cluster/cluster_redirection_test.go
=> Integration testing: cluster tx redirection

internal/replication/blockreplicator.go, internal/replication/blockreplicator_3node_test.go
=> Run initial campaign on new cluster

pkg/server/server_test.go
=> change server test port

test/cluster/add_node_test.go, test/cluster/remove_node_test.go
=> fix remove node test

test/cluster/add_node_test.go, test/cluster/security_test.go, test/setup/cluster_setup.go, test/setup/server_setup.go
=> Integration testing - cluster security TLS

pkg/server/mock/rest_client.go, test/cluster/add_node_test.go, test/queries/range_query_test.go, test/setup/cluster_setup.go, test/setup/server_setup.go
=> range query test

pkg/server/mock/rest_client.go, test/queries/ledger_test.go, test/setup/server_setup.go
=> data proof test

test/queries/provenance_acl_test.go, test/queries/provenance_switch_off_test.go, test/queries/provenance_test.go, test/setup/server_setup.go
=> provenance test - ACLs on data and operations

internal/httphandler/data_request_handler.go, internal/httphandler/data_request_handler_test.go
Fix response status code to unauthorized when the request is not signed properly
=> Fix response status code

pkg/cryptoservice/verifier.go
=> Fix logging call

test/queries/ledger_test.go
Signed-off-by: May Rosenbaum <mayro1595@gmail.com>
=> Fix txsNumInBlocks

internal/blockprocessor/committer.go
=> Avoid preparing data when provenance is disabled

internal/bcdb/worldstate_query_processor.go, internal/bcdb/worldstate_query_processor_test.go, test/db/db_index_management_test.go, test/setup/server_setup.go, test/user/user_db_acl_test.go, test/user/user_update_acl_test.go
=> Access control on reading user records during a query

internal/identity/querier.go, internal/identity/querier_test.go, internal/txvalidation/useradmin_tx_validator.go, internal/txvalidation/useradmin_tx_validator_test.go, test/setup/server_setup.go, test/user/user_update_acl_test.go
Signed-off-by: May Rosenbaum <mayro1595@gmail.com>
=> Access control on writing user records - restrictive - stage 2

docs/architecture-and-design/block-structure.md, docs/getting-started/proofs-and-verification/curl/block.md, docs/getting-started/proofs-and-verification/curl/state.md, docs/getting-started/proofs-and-verification/gosdk/state.md, docs/getting-started/queries/curl/block-header.md, docs/getting-started/queries/curl/provenance.md, docs/getting-started/queries/curl/transaction-receipt.md, docs/getting-started/transactions/curl/datatx.md, docs/getting-started/transactions/curl/dbtx.md, docs/getting-started/transactions/curl/usertx.md
Signed-off-by: May Rosenbaum <mayro1595@gmail.com>
=> Fixing merkle typo - documentation

go.mod, go.sum, internal/worldstate/leveldb/cache.go, internal/worldstate/leveldb/cache_test.go, internal/worldstate/leveldb/commit_and_query.go, internal/worldstate/leveldb/commit_and_query_test.go, internal/worldstate/leveldb/open.go, internal/worldstate/leveldb/snapshot_test.go
=> cache for states

pkg/server/testutils/crypto_utils.go
A temporary directory that PR #481 missed.
=> Use testing.TempDir()

internal/bcdb/db.go, internal/bcdb/ledger_query_procesor.go, internal/bcdb/ledger_query_procesor_test.go, internal/httphandler/config_request_handler_test.go, internal/httphandler/data_request_handler_test.go, internal/httphandler/db_request_handler_test.go, internal/httphandler/users_request_handler_test.go, internal/httphandler/utils.go, internal/txvalidation/sig_validator.go, internal/utils/http.go, pkg/cryptoservice/signer.go, pkg/marshal/proto_json_marshal.go, pkg/server/mock/rest_client.go, pkg/server/server_test.go, pkg/server/testutils/crypto_utils.go
=> Avoid instantiating the default marshaller before each use

pkg/server/testutils/crypto_utils.go
This is used by Orion's benchmark to issue certificates for the servers.
=> Allow issuing cert with URI instead of IP
